language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
install:
    - "pip install ."
    - "pip install flake8"
    - "pip install coveralls"
script:
    - "flake8 greb"
    - "flake8 test"
    - "coverage run --source=greb -m test.test_greb"
after_script:
    - coveralls